version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "astro" # Handle Astro manually due to breaking changes
    # Disable auto-merge while CI stability is verified
    allow-auto-merge: false
  # Maintain github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "ci"